/* SPDX-License-Identifier: Apache-2.0
 *
 * inkling_cache_sim.c — drive WASTE's REAL expert cache with an Inkling
 * routing trace and report what it actually does.
 *
 * docs/GATES.md Gate 2 simulated LRU-vs-LFRU hit curves in Python and Gate 5
 * then measured that the real cache beats the simulation above 12%. So a
 * second Python reimplementation of the policy would be answering a question
 * whose answer is already known to be wrong. This links `src/ecache.c` and
 * runs the shipping LFRU implementation — sampled eviction, frequency-first
 * ordering, hash table and all — over a trace generated by
 * `inkling_cache_trace.py`.
 *
 * Nothing here touches a disk: `fetch` returns immediately. The measurement is
 * placement, not bandwidth, and every read this reports as a miss is a read
 * the engine would have issued.
 *
 * Build: cc -O2 -std=gnu11 -I<waste/src> -o inkling_cache_sim \
 *            inkling_cache_sim.c <waste/src>/ecache.c -lpthread
 * Usage: inkling_cache_sim TRACE.bin CACHE_BYTES REC_BYTES [policy]
 *        policy 0 = LFRU (shipping default), 1 = LRU
 *
 * Prints one JSON object on stdout.
 *
 * Trace format, little-endian, produced by inkling_cache_trace.py:
 *   u32 magic 'ICT1', u32 steps, u32 layers, u32 slots_per_layer
 *   then steps*layers records of: u32 n, then n * u32 expert ids
 * A "step" is one decode position for batch 1, or one chunk of positions when
 * the generator was asked to dedup — which is what `moe_chunk` does upstream,
 * so a chunk's record count is the number of distinct records it needs.
 */
#define _GNU_SOURCE
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "ecache.h"

#define TRACE_MAGIC 0x31544349u   /* 'ICT1' little-endian */

/* The cache only cares that fetch succeeds and fills rec_bytes. Filling it
 * with anything real would measure memset, not placement. */
static size_t g_rec;
static uint64_t g_fetches;

static int sim_fetch(void *user, int layer, int expert, uint8_t *dst)
{
    (void)user; (void)layer; (void)expert;
    g_fetches++;
    /* Touch one byte per page so the allocation is real without paying for a
     * full memset of a 9 MB record on every miss. dst is NULL only on the
     * no-cache path, where there is no slot to touch. */
    if (dst)
        for (size_t off = 0; off < g_rec; off += 4096) dst[off] = 1;
    return 0;
}

static uint32_t rd_u32(FILE *f, const char *what)
{
    uint32_t v;
    if (fread(&v, sizeof v, 1, f) != 1) {
        fprintf(stderr, "inkling_cache_sim: truncated trace reading %s\n", what);
        exit(2);
    }
    return v;
}

int main(int argc, char **argv)
{
    if (argc < 4) {
        fprintf(stderr,
                "usage: %s TRACE.bin CACHE_BYTES REC_BYTES [policy]\n",
                argv[0]);
        return 1;
    }
    const char *path = argv[1];
    const size_t budget = strtoull(argv[2], NULL, 10);
    const size_t rec = strtoull(argv[3], NULL, 10);
    const int policy = argc > 4 ? atoi(argv[4]) : 0;

    if (rec == 0 || rec % 4096) {
        fprintf(stderr, "inkling_cache_sim: record must be a positive multiple of 4096\n");
        return 1;
    }
    g_rec = rec;

    FILE *f = fopen(path, "rb");
    if (!f) { perror("open trace"); return 1; }
    if (rd_u32(f, "magic") != TRACE_MAGIC) {
        fprintf(stderr, "inkling_cache_sim: not an ICT1 trace\n");
        return 2;
    }
    const uint32_t steps = rd_u32(f, "steps");
    const uint32_t layers = rd_u32(f, "layers");
    const uint32_t slots = rd_u32(f, "slots_per_layer");
    if (!steps || !layers || !slots) {
        fprintf(stderr, "inkling_cache_sim: empty trace\n");
        return 2;
    }

    waste_ecache c;
    if (waste_ecache_init(&c, budget, rec, policy) != 0) {
        fprintf(stderr, "inkling_cache_sim: cache init refused "
                        "(budget %zu, record %zu)\n", budget, rec);
        return 3;
    }

    uint64_t accesses = 0;
    int *ids = NULL;
    uint32_t ids_cap = 0;

    for (uint32_t s = 0; s < steps; s++) {
        for (uint32_t L = 0; L < layers; L++) {
            const uint32_t n = rd_u32(f, "record count");
            if (n > ids_cap) {
                ids = realloc(ids, (size_t)n * sizeof *ids);
                if (!ids) { fprintf(stderr, "oom\n"); return 4; }
                ids_cap = n;
            }
            for (uint32_t i = 0; i < n; i++) {
                const uint32_t e = rd_u32(f, "expert id");
                if (e >= slots) {
                    fprintf(stderr, "inkling_cache_sim: expert %u outside "
                                    "0..%u\n", e, slots - 1);
                    return 2;
                }
                ids[i] = (int)e;
            }
            /* Name the layer's records before reading any of them. With a
             * synchronous cache this is a no-op, which is the point: the
             * demand stream must measure the same either way. */
            waste_ecache_hint(&c, (int)L, ids, (int)n);
            for (uint32_t i = 0; i < n; i++) {
                if (c.n_slots == 0) {
                    /* ecache.h says a zero budget "disables caching (every
                     * access reads)", but waste_ecache_get has no slot to
                     * return and answers NULL — at a zero budget the engine
                     * reads directly rather than calling it. Model that here
                     * instead of reporting a failure, so the no-cache column
                     * is the honest all-miss baseline it claims to be. */
                    c.misses++;
                    c.bytes_read += rec;
                    sim_fetch(NULL, (int)L, ids[i], NULL);
                } else if (!waste_ecache_get(&c, (int)L, ids[i], sim_fetch, NULL)) {
                    fprintf(stderr, "inkling_cache_sim: get failed at "
                                    "layer %u expert %d\n", L, ids[i]);
                    return 5;
                }
                accesses++;
            }
        }
    }
    fclose(f);

    /* bytes_read is what the disk would have moved; per-step is the number
     * that multiplies into seconds. */
    const double per_step = (double)c.bytes_read / (double)steps;
    printf("{\"steps\":%u,\"layers\":%u,\"slots_per_layer\":%u,"
           "\"accesses\":%llu,\"hits\":%llu,\"misses\":%llu,"
           "\"evictions\":%llu,\"fetches\":%llu,"
           "\"n_slots\":%d,\"budget_bytes\":%zu,\"rec_bytes\":%zu,"
           "\"policy\":%d,\"hit_rate\":%.6f,\"bytes_read\":%llu,"
           "\"bytes_per_step\":%.1f}\n",
           steps, layers, slots,
           (unsigned long long)accesses,
           (unsigned long long)c.hits,
           (unsigned long long)c.misses,
           (unsigned long long)c.evictions,
           (unsigned long long)g_fetches,
           c.n_slots, budget, rec, policy,
           waste_ecache_hit_rate(&c),
           (unsigned long long)c.bytes_read,
           per_step);

    free(ids);
    waste_ecache_free(&c);
    return 0;
}
